apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ3aXR0bWFuOCIsInBhc3N3b3JkIjoiQWxsYWNoIzMzIiwiZW1haWwiOiJ0b2JpYXMud2l0dG1hbm5AaG0uZWR1IiwiYXV0aCI6ImQybDBkRzFoYmpnNlFXeHNZV05vSXpNeiJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Values.image.tag }}-apnmtregcred
  namespace: apnmt
type: kubernetes.io/dockerconfigjson
