apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.image.tag }}
  namespace: {{ .Release.Namespace }}
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas | default 3 }}
  minReplicas: {{ .Values.hpa.minReplicas | default 1 }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.image.tag }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage | default 80}}
