apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: opening-hour-changed
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 100
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
