apiVersion: v1
kind: Pod
metadata:
  name: preinstall-hook
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  containers:
    - name: pre-install-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'kubectl wait --timeout=90s --for=condition=available deployment emissary-apiext -n emissary-system' ]
  restartPolicy: Never
  terminationGracePeriodSeconds: 0