cluster:
  name: ""

limits:
  resources:
    cpu: 50
    memory: 50Gi

requirements:
  capaccityType:
    values:
      - "spot"
  instanceType:
    values:
      - "t2.micro"
  zones:
    values:
      - "eu-central-1a"
