# Values will be defined by service.

mongodb:
  resources:
    limits:
      cpu: 2
      memory: 4Gi
  auth:
    rootUser: root
    rootPassword: Uz7GnNqGEUkf
  architecture: standalone
  replicaCount: 1

hpa:
  maxReplicas: 3
  minReplicas: 1
  targetCPUUtilizationPercentage: 50